name: "Export ISO 📀"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    name: Build ISO
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      
      - name: Enable Nix Flakes
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Build ISO
        run: |
          nix build .#nixosConfigurations.iso.config.system.build.isoImage
          
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: nixos-iso
          path: result/iso/*.iso